## Deep Learning
### Examen Agosto 2022

#### Alumna: Ariadna Garmendia

#### 4) Se tiene la función y = a * log(b) + b * c^2. Calcular las derivadas de y respecto a los parámetros a, b, c, evaluando en los valores a=2, b=10, c=0.5. Se deben calcular las derivadas por los siguientes métodos:


#### * Utilizando derivadas analíticas (symbolic differentiation).

#### * Utilizando límite con un delta numérico pequeño (numerical differentiation).

#### * Utilizando grafos y la regla de la cadena (chain rule differentiation)

"![grafos.jpg](attachment:grafos.jpg)"

#### * Utilizando PyTorch (automatic differentiation). 

In [6]:
import torch

In [7]:
a = torch.tensor([2.], requires_grad=True) #Inicializo tensor a
b = torch.tensor([10.], requires_grad=True) #Inicializo tensor b
c = torch.tensor([0.5], requires_grad=True) #Inicializo tensor c

In [8]:
d = torch.square(c)
e = b * d
f = torch.log10(b)
g = a * f
y = e + g

In [9]:
y

tensor([4.5000], grad_fn=<AddBackward0>)

In [10]:
y = y.backward()

In [11]:
a.grad

tensor([1.])

In [12]:
b.grad

tensor([0.3369])

In [13]:
c.grad

tensor([10.])